### ISSUE TITLE
rename repo?

### ISSUE THREAD

**Issue by cephillips** [stanfordjournalism/padj23-code#1]
Should we rename this repo to padj2324-code?
Or create anew repo for winter quarter?
Getting Serdar's opinion.

**Comment by zstumgoren** [comment]
Would be good to keep everything in one repo. Can rename

**Comment by zstumgoren** [comment]
Keeping the generic `padj-code` repo to simplify year-to-year migrations. Have generalized the material here (much of it from the old programming in journalism repo) and, if we find it necessary, can use git tags to label content by year
